#cloud-config

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - nginx
  - docker-ce
  - docker-ce-cli


runcmd:
  - printf "user www-data;\n
    worker_processes auto;\n
    worker_cpu_affinity auto;\n
    pid /run/nginx.pid;\n
    error_log /var/log/nginx/error.log;\n
    include /etc/nginx/modules-enabled/*.conf;\n
    events {\n
            \tworker_connections 768;\n
    }\n
    http {\n
            \tserver {\n
                    \t\tlisten 80;\n
                    \t\tlocation / {\n
                            \t\t\tproxy_pass http://localhost:8000;\n
                    \t\t}\n
            \t}\n
    }" > /etc/nginx/nginx.conf
  - sudo nginx -s reload
  - sudo git clone https://github.com/pulszar/cloud-deployment.git /opt/cloud-deployment
  - sudo docker compose -f /opt/cloud-deployment/docker-compose.yaml up
  - sudo git config --global --add safe.directory /opt/cloud-deployment
