name: Deploy app to server

on:
  push:
    branches:
      - feature/actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test from runner
        run: echo "Hello from runner"